#page title
page_title                                : Lyric Fever                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://github.com/aviwad/SpotifyLyricsInMenubar/releases/download/v1.6/Lyric.Fever.app.zip                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Lyric Fever                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Spotify Lyrics in the menubar.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Avi Wadhwa                                
your_link                                 : https://aviwadhwa.com                     
your_city                                 : Vancouver                                
email_address                             : aviwad@gmail.com
facebook_username                         :                                           
instagram_username                        : aviwad
twitter_username                          : 
github_username                           : aviwad
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Real-Time Spotify Lyrics
    description                           : Stay connected with your friends in real-time. See what they're listening to, right as it happens. Our app automatically refreshes and animates changes, providing a seamless experience.
    fontawesome_icon_name                 : spinner
    
  - title                                 : Just Install And Use
    description                           : Access your Spotify friend activity directly from your home screen with our intuitive widgets. Stay updated without even opening the app.
    fontawesome_icon_name                 : mobile

  - title                                 : Auto-Downloads Lyrics
    description                           : Experience a sleek and modern design crafted with SwiftUI. Our app is optimized for smooth performance, providing a delightful user experience.
    fontawesome_icon_name                 : brush

  - title                                 : No Need To Set Anything Up
    description                           : Immerse yourself in the music world with rich visuals. Our app displays album art and user photos, adding a visual dimension to your Spotify friend activity.
    fontawesome_icon_name                 : palette

  - title                                 : Ad-Free Experience
    description                           : Enjoy an uninterrupted experience with our ad-free app. Say goodbye to annoying ads and focus solely on connecting with your friends and enjoying music.
    fontawesome_icon_name                 : heart

  - title                                 : 10 Daily users
    description                           : What are you waiting for? You could be the 11th!
    fontawesome_icon_name                 : Download Now

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#57B65F"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#57B65F"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#57B65F"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"












####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
